name: log
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      - ZO_ROOT_USER_EMAIL=admin@kowiste.com
      - ZO_ROOT_USER_PASSWORD=admin123
      - ZO_STORAGE_TYPE=disk
      - ZO_DATA_DIR=/data
      - ZO_LOG_RETENTION_DAYS=3    # 3-day retention
      - ZO_COMPACT_DAYS=1          # Daily compaction
      # Optional performance tuning
      - ZO_MEMORY_CACHE_MAX_SIZE=1073741824  # 1GB cache
      - ZO_MEMORY_CACHE_CLEAN_INTERVAL=60     # Clean cache every 60 seconds
      # Optional compression settings
      - ZO_COMPRESSION_ENABLED=true
      - ZO_COMPRESSION_MIN_SIZE=1024          # Min size for compression (1KB)
    ports:
      - "5080:5080"    # UI and API port
    volumes:
      - openobserve_data:/data    # Persistent storage
    restart: unless-stopped        # Automatically restart if it crashes
    logging:
      driver: "json-file"
      options:
        max-size: "50m"           # Max log size for the container itself
        max-file: "3"             # Keep 3 rotated log files

volumes:
  openobserve_data:               # Define persistent volume