# config/config.yaml
app:
  name: asset-service
  environment: development
  log_level: debug

http:
  host: 0.0.0.0
  port: 8080
  shutdown_timeout: 5s
  read_timeout: 15s
  write_timeout: 15s
  cors_allowed_origins:
    - http://localhost:3000
    - https://your-frontend-domain.com

grpc:
  host: 0.0.0.0
  port: 9090

database:
  driver: postgres  # or sqlite
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: asset_service
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h
  auto_migrate: true

nats:
  url: nats://localhost:4222
  cluster: asset-service-cluster
  client: asset-service
  timeout: 10s

jwt:
  secret: your-secret-key-here
  expiration_time: 24h
  refresh_duration: 72h

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_interval: 30s
  max_message_size: 512000  # 512KB

telemetry:
  service_name: kowiste
  environment: local
  endpoint: localhost:5080
  tracing_enabled: true
  sampling_rate: 1.0
  headers: YWRtaW5Aa293aXN0ZS5jb206YWRtaW4xMjM=
  metrics_enabled: true
  metrics_host: 0.0.0.0
  metrics_port: 9100